[tool.briefcase]
project_name = "wce"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/wce"
license = "BSD license"
author = 'WanomiR'
author_email = "i@wanomir.ru"

[tool.briefcase.app.app]
formal_name = "taxi_app"
description = "Taxi orders number prediction app"
sources = ['src/app']
requires = [
            'etna==1.15.0',
            'path.py',
            'streamlit',
]